### ISSUE TITLE
#1 - Changing to labeling for the files 

### ISSUE THREAD

**Issue by Marquez-Brown** [Marquez-Brown/project-2#5]
Overarching user story:
As a user who is looking for a new song to listen to or discover
I want to be able to see all of the songs listed in a ranked order, be able to play and submit songs
So that I know what the highest ranked songs are 
Issue user story:
As a developer who is accessing the code to work on it
I want to be able have all of the files organized
So that I know how how to complete my tasks 

Acceptance criteria:
Given that the project code is accessed
When a developer wants to work on a file
They are presented a file that is labeled for this project (change trains to wavelength)

**Comment by KevinB04** [comment]
Good to go!
